<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProjectFeaturesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('project_features')->delete();
        
        \DB::table('project_features')->insert(array (
            0 => 
            array (
                'id' => 63,
                'project_id' => 1,
                'name' => 'Master Company',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-001',
                'fsd_code' => 'FSD-001',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            1 => 
            array (
                'id' => 64,
                'project_id' => 1,
                'name' => 'Master Branch',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-002',
                'fsd_code' => 'FSD-002',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            2 => 
            array (
                'id' => 65,
                'project_id' => 1,
            'name' => 'Master Storage Location (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-003',
                'fsd_code' => 'FSD-003',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            3 => 
            array (
                'id' => 66,
                'project_id' => 1,
                'name' => 'Master User & Role Permission',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-004',
                'fsd_code' => 'FSD-004',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            4 => 
            array (
                'id' => 67,
                'project_id' => 1,
            'name' => 'Business Partner Grouping & Role (Customer/Vendor Type) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-005',
                'fsd_code' => 'FSD-005',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            5 => 
            array (
                'id' => 68,
                'project_id' => 1,
            'name' => 'Master Document Type Definition (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-006',
                'fsd_code' => 'FSD-006',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            6 => 
            array (
                'id' => 69,
                'project_id' => 1,
            'name' => 'Transaction Type Definition (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-007',
                'fsd_code' => 'FSD-007',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            7 => 
            array (
                'id' => 70,
                'project_id' => 1,
            'name' => 'Document Type Mapping (Cross-Module Integration) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-008',
                'fsd_code' => 'FSD-008',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            8 => 
            array (
                'id' => 71,
                'project_id' => 1,
            'name' => 'Currency & Exchange Rate (Mata Uang & Kurs) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-009',
                'fsd_code' => 'FSD-009',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            9 => 
            array (
                'id' => 72,
                'project_id' => 1,
            'name' => 'Accounting Period & Variant (Open/Close Period)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-010',
                'fsd_code' => 'FSD-010',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            10 => 
            array (
                'id' => 73,
                'project_id' => 1,
                'name' => 'Document Numbering Engine',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-011',
                'fsd_code' => 'FSD-011',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            11 => 
            array (
                'id' => 74,
                'project_id' => 1,
            'name' => 'GL Account Group & Field Status Configuration (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-012',
                'fsd_code' => 'FSD-012',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            12 => 
            array (
                'id' => 75,
                'project_id' => 1,
            'name' => 'Retained Earnings & Year-End Closing Rules (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-013',
                'fsd_code' => 'FSD-013',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            13 => 
            array (
                'id' => 76,
                'project_id' => 1,
            'name' => 'Chart of Accounts (COA)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-014',
                'fsd_code' => 'FSD-014',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            14 => 
            array (
                'id' => 77,
                'project_id' => 1,
            'name' => 'House Bank & Bank Account Master Setup (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-015',
                'fsd_code' => 'FSD-015',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            15 => 
            array (
                'id' => 78,
                'project_id' => 1,
            'name' => 'Controlling Area & Standard Hierarchy Configuration (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-016',
                'fsd_code' => 'FSD-016',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            16 => 
            array (
                'id' => 79,
                'project_id' => 1,
            'name' => 'Cost Center Management (Pusat Biaya)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-017',
                'fsd_code' => 'FSD-017',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            17 => 
            array (
                'id' => 80,
                'project_id' => 1,
            'name' => 'Accounting Document Architecture (Journal Entries) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-018',
                'fsd_code' => 'FSD-018',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            18 => 
            array (
                'id' => 81,
                'project_id' => 1,
            'name' => 'Auto Journal Mapping (Posting Matrix)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-019',
                'fsd_code' => 'FSD-019',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            19 => 
            array (
                'id' => 82,
                'project_id' => 1,
            'name' => 'Tax Configuration (Setup Pajak & Tax Code) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-020',
                'fsd_code' => 'FSD-020',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            20 => 
            array (
                'id' => 83,
                'project_id' => 1,
            'name' => 'Global Unit of Measure (UOM) & Dimension (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-021',
                'fsd_code' => 'FSD-021',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            21 => 
            array (
                'id' => 84,
                'project_id' => 1,
            'name' => 'Material Type Configuration (Tipe Material) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-022',
                'fsd_code' => 'FSD-022',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            22 => 
            array (
                'id' => 85,
                'project_id' => 1,
            'name' => 'Transaction Item Category Configuration (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-023',
                'fsd_code' => 'FSD-023',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            23 => 
            array (
                'id' => 86,
                'project_id' => 1,
            'name' => 'Valuation Class Configuration (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-024',
                'fsd_code' => 'FSD-024',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            24 => 
            array (
                'id' => 87,
                'project_id' => 1,
            'name' => 'Reason Code Configuration (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-025',
                'fsd_code' => 'FSD-025',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            25 => 
            array (
                'id' => 88,
                'project_id' => 1,
            'name' => 'Movement Type Configuration (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-026',
                'fsd_code' => 'FSD-026',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            26 => 
            array (
                'id' => 89,
                'project_id' => 1,
            'name' => 'Account Determination (Auto Posting Mapping)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-027',
                'fsd_code' => 'FSD-027',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            27 => 
            array (
                'id' => 90,
                'project_id' => 1,
            'name' => 'Employee & Job Position Master (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-028',
                'fsd_code' => 'FSD-028',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            28 => 
            array (
                'id' => 91,
                'project_id' => 1,
            'name' => 'Approval Level Matrix (ALM) / Release Strategy (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-029',
                'fsd_code' => 'FSD-029',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            29 => 
            array (
                'id' => 92,
                'project_id' => 1,
            'name' => 'Tolerance Limit Rules (GR, Invoice & Stock) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-030',
                'fsd_code' => 'FSD-030',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            30 => 
            array (
                'id' => 93,
                'project_id' => 1,
            'name' => 'Credit Limit & Risk Management Rules (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-031',
                'fsd_code' => 'FSD-031',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            31 => 
            array (
                'id' => 94,
                'project_id' => 1,
            'name' => 'Term of Payment (TOP) Setup (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-032',
                'fsd_code' => 'FSD-032',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            32 => 
            array (
                'id' => 95,
                'project_id' => 1,
            'name' => 'Sales Organization Structure (Sales Org, Dist Channel) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-033',
                'fsd_code' => 'FSD-033',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            33 => 
            array (
                'id' => 96,
                'project_id' => 1,
            'name' => 'Purchasing Organization Structure (Purch Org, Purch Group) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-034',
                'fsd_code' => 'FSD-034',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            34 => 
            array (
                'id' => 97,
                'project_id' => 1,
            'name' => 'Enterprise Structure Assignment & Hierarchy Mapping (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-035',
                'fsd_code' => 'FSD-035',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            35 => 
            array (
                'id' => 98,
                'project_id' => 1,
            'name' => 'Pricing Access Sequence & Condition Table Engine (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-036',
                'fsd_code' => 'FSD-036',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            36 => 
            array (
                'id' => 99,
                'project_id' => 1,
            'name' => 'Master Condition Type (Pricing Configuration) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-037',
                'fsd_code' => 'FSD-037',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            37 => 
            array (
                'id' => 100,
                'project_id' => 1,
                'name' => 'Pricing Structure Pembelian & Determination Matrix',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-038',
                'fsd_code' => 'FSD-038',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            38 => 
            array (
                'id' => 101,
                'project_id' => 1,
                'name' => 'Sales Pricing Structure & Determination Matrix',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-039',
                'fsd_code' => 'FSD-039',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 1,
            'description' => 'Fitur Konfigurasi Dasar (Wajib)',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            39 => 
            array (
                'id' => 102,
                'project_id' => 1,
            'name' => 'Data Barang & Satuan (Mencakup Material & Jasa)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-040',
                'fsd_code' => 'FSD-040',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            40 => 
            array (
                'id' => 103,
                'project_id' => 1,
            'name' => 'Serial Number & Batch/Expiry Master (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-041',
                'fsd_code' => 'FSD-041',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            41 => 
            array (
                'id' => 104,
                'project_id' => 1,
            'name' => 'Customer Master Data (Enterprise Refinement)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-042',
                'fsd_code' => 'FSD-042',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            42 => 
            array (
                'id' => 105,
                'project_id' => 1,
            'name' => 'Vendor Master Data (Enterprise Alignment)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-043',
                'fsd_code' => 'FSD-043',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            43 => 
            array (
                'id' => 106,
                'project_id' => 1,
            'name' => 'Fixed Asset Master Data (Aktiva Tetap) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-044',
                'fsd_code' => 'FSD-044',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            44 => 
            array (
                'id' => 107,
                'project_id' => 1,
            'name' => 'Setup Master Harga Beli (Purchase Price List)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-045',
                'fsd_code' => 'FSD-045',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            45 => 
            array (
                'id' => 108,
                'project_id' => 1,
            'name' => 'Purchase Requisition (PR)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-046',
                'fsd_code' => 'FSD-046',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            46 => 
            array (
                'id' => 109,
                'project_id' => 1,
            'name' => 'Request for Quotation (RFQ)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-047',
                'fsd_code' => 'FSD-047',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            47 => 
            array (
                'id' => 110,
                'project_id' => 1,
            'name' => 'Quotation Comparison Form (QCF)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-048',
                'fsd_code' => 'FSD-048',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            48 => 
            array (
                'id' => 111,
                'project_id' => 1,
            'name' => 'Purchase Contract (Outline Agreement) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-049',
                'fsd_code' => 'FSD-049',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            49 => 
            array (
                'id' => 112,
                'project_id' => 1,
            'name' => 'Purchase Order (PO)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-050',
                'fsd_code' => 'FSD-050',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            50 => 
            array (
                'id' => 113,
                'project_id' => 1,
            'name' => 'Goods Receipt (GR)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-051',
                'fsd_code' => 'FSD-051',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            51 => 
            array (
                'id' => 114,
                'project_id' => 1,
            'name' => 'Supplier Return (Retur Pembelian)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-052',
                'fsd_code' => 'FSD-052',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            52 => 
            array (
                'id' => 115,
                'project_id' => 1,
            'name' => 'Stock Transfer (Mutasi Antar Gudang)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-053',
                'fsd_code' => 'FSD-053',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            53 => 
            array (
                'id' => 116,
                'project_id' => 1,
            'name' => 'Internal Goods Issue (Penggunaan Internal & Scrap) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-054',
                'fsd_code' => 'FSD-054',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            54 => 
            array (
                'id' => 117,
                'project_id' => 1,
            'name' => 'Stock Adjustment (Opname)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-055',
                'fsd_code' => 'FSD-055',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            55 => 
            array (
                'id' => 118,
                'project_id' => 1,
            'name' => 'Setup Master Harga Jual (Sales Price List)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-057',
                'fsd_code' => 'FSD-056',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:46',
            ),
            56 => 
            array (
                'id' => 119,
                'project_id' => 1,
            'name' => 'Customer Quotation (Penawaran Penjualan)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-058',
                'fsd_code' => 'FSD-057',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            57 => 
            array (
                'id' => 120,
                'project_id' => 1,
            'name' => 'Sales Order (SO) & Advanced Enterprise Engine',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-059',
                'fsd_code' => 'FSD-058',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            58 => 
            array (
                'id' => 121,
                'project_id' => 1,
            'name' => 'Outbound Delivery & Goods Issue (Pengiriman Barang Penjualan)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-060',
                'fsd_code' => 'FSD-059',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:33',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            59 => 
            array (
                'id' => 122,
                'project_id' => 1,
            'name' => 'Customer Return (Retur Penjualan)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-061',
                'fsd_code' => 'FSD-060',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            60 => 
            array (
                'id' => 123,
                'project_id' => 1,
            'name' => 'Shipment Management (Logistics Ekspedisi)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-062',
                'fsd_code' => 'FSD-061',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            61 => 
            array (
                'id' => 124,
                'project_id' => 1,
                'name' => 'Shipment Cost Management',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-063',
                'fsd_code' => 'FSD-062',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            62 => 
            array (
                'id' => 125,
                'project_id' => 1,
                'name' => 'Bill of Material & Work Order',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-064',
                'fsd_code' => 'FSD-063',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            63 => 
            array (
                'id' => 126,
                'project_id' => 1,
                'name' => 'AP Invoice',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-065',
                'fsd_code' => 'FSD-064',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            64 => 
            array (
                'id' => 127,
                'project_id' => 1,
            'name' => 'Vendor Down Payment (Uang Muka Vendor)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-066',
                'fsd_code' => 'FSD-065',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            65 => 
            array (
                'id' => 128,
                'project_id' => 1,
            'name' => 'Payment Proposal (Proposal Pembayaran)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-067',
                'fsd_code' => 'FSD-066',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            66 => 
            array (
                'id' => 129,
                'project_id' => 1,
            'name' => 'Vendor Payment (Payment Voucher)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-068',
                'fsd_code' => 'FSD-067',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            67 => 
            array (
                'id' => 130,
                'project_id' => 1,
            'name' => 'Customer Down Payment (Uang Muka Pelanggan) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-068',
                'fsd_code' => 'FSD-068',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            68 => 
            array (
                'id' => 131,
                'project_id' => 1,
                'name' => 'AR Invoice',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-070',
                'fsd_code' => 'FSD-069',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            69 => 
            array (
                'id' => 132,
                'project_id' => 1,
                'name' => 'Customer Payment',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-071',
                'fsd_code' => 'FSD-070',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            70 => 
            array (
                'id' => 133,
                'project_id' => 1,
                'name' => 'Petty Cash',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-072',
                'fsd_code' => 'FSD-071',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            71 => 
            array (
                'id' => 134,
                'project_id' => 1,
            'name' => 'General Ledger (Memorial Journal)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-073',
                'fsd_code' => 'FSD-072',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            72 => 
            array (
                'id' => 135,
                'project_id' => 1,
            'name' => 'Manual Bank Statement (Rekening Koran Manual)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-074',
                'fsd_code' => 'FSD-073',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            73 => 
            array (
                'id' => 136,
                'project_id' => 1,
            'name' => 'Foreign Exchange Revaluation (Revaluasi Kurs Bulanan)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-075',
                'fsd_code' => 'FSD-074',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            74 => 
            array (
                'id' => 137,
                'project_id' => 1,
                'name' => 'Month-End Closing Programs',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-076',
                'fsd_code' => 'FSD-075',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            75 => 
            array (
                'id' => 138,
                'project_id' => 1,
                'name' => 'Trial Balance',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-077',
                'fsd_code' => 'FSD-076',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            76 => 
            array (
                'id' => 139,
                'project_id' => 1,
            'name' => 'Laba Rugi (Profit & Loss)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-078',
                'fsd_code' => 'FSD-077',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            77 => 
            array (
                'id' => 140,
                'project_id' => 1,
            'name' => 'Neraca (Balance Sheet)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-079',
                'fsd_code' => 'FSD-078',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            78 => 
            array (
                'id' => 141,
                'project_id' => 1,
            'name' => 'Laporan Arus Kas (Cash Flow)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-080',
                'fsd_code' => 'FSD-079',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            79 => 
            array (
                'id' => 142,
                'project_id' => 1,
            'name' => 'Laporan Master Data Barang (Item Master List)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-081',
                'fsd_code' => 'FSD-080',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            80 => 
            array (
                'id' => 143,
                'project_id' => 1,
            'name' => 'Laporan Master Data Pelanggan (Customer Directory)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-082',
                'fsd_code' => 'FSD-081',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            81 => 
            array (
                'id' => 144,
                'project_id' => 1,
            'name' => 'Laporan Master Data Supplier (Supplier Directory)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-083',
                'fsd_code' => 'FSD-082',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            82 => 
            array (
                'id' => 145,
                'project_id' => 1,
            'name' => 'Laporan Master Data COA (Chart of Accounts List)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-084',
                'fsd_code' => 'FSD-083',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            83 => 
            array (
                'id' => 146,
                'project_id' => 1,
            'name' => 'Laporan Purchase Order (PO Report)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-085',
                'fsd_code' => 'FSD-084',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            84 => 
            array (
                'id' => 147,
                'project_id' => 1,
            'name' => 'Laporan Penerimaan Barang (GR Log)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-086',
                'fsd_code' => 'FSD-085',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            85 => 
            array (
                'id' => 148,
                'project_id' => 1,
            'name' => 'Laporan Unbilled Goods (Goods Receipt Not Invoiced)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-087',
                'fsd_code' => 'FSD-086',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            86 => 
            array (
                'id' => 149,
                'project_id' => 1,
            'name' => 'Kartu Stok (Stock Card)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-088',
                'fsd_code' => 'FSD-087',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            87 => 
            array (
                'id' => 150,
                'project_id' => 1,
            'name' => 'Laporan Mutasi Stok (Stock Movement)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-089',
                'fsd_code' => 'FSD-088',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            88 => 
            array (
                'id' => 151,
                'project_id' => 1,
                'name' => 'Laporan Stock Aging',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-090',
                'fsd_code' => 'FSD-089',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            89 => 
            array (
                'id' => 152,
                'project_id' => 1,
            'name' => 'Laporan Valuasi Persediaan (Inventory Valuation)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-091',
                'fsd_code' => 'FSD-090',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            90 => 
            array (
                'id' => 153,
                'project_id' => 1,
            'name' => 'Laporan Penjualan (Sales Report by Sales Order)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-093',
                'fsd_code' => 'FSD-091',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            91 => 
            array (
                'id' => 154,
                'project_id' => 1,
            'name' => 'Laporan Penjualan (Sales Report by AR Invoice) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-092',
                'fsd_code' => 'FSD-092',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            92 => 
            array (
                'id' => 155,
                'project_id' => 1,
            'name' => 'Laporan Piutang (Report AR)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-095',
                'fsd_code' => 'FSD-093',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            93 => 
            array (
                'id' => 156,
                'project_id' => 1,
            'name' => 'Laporan Rincian Piutang (Customer Line Item) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-096',
                'fsd_code' => 'FSD-096',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:56:41',
            ),
            94 => 
            array (
                'id' => 157,
                'project_id' => 1,
                'name' => 'Laporan AR Aging',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-097',
                'fsd_code' => 'FSD-095',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            95 => 
            array (
                'id' => 158,
                'project_id' => 1,
                'name' => 'Laporan AP Aging',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-098',
                'fsd_code' => 'FSD-096',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:51:47',
            ),
            96 => 
            array (
                'id' => 159,
                'project_id' => 1,
            'name' => 'Laporan Rincian Hutang (Vendor Line Item) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-099',
                'fsd_code' => 'FSD-099',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:56:41',
            ),
            97 => 
            array (
                'id' => 160,
                'project_id' => 1,
            'name' => 'Laporan Buku Besar (GL Line Item Display) (New)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-100',
                'fsd_code' => 'FSD-100',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-21 13:00:34',
                'updated_at' => '2026-07-25 04:56:41',
            ),
            98 => 
            array (
                'id' => 163,
                'project_id' => 1,
            'name' => 'Laporan Laba Rugi (Profit & Loss)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-101',
                'fsd_code' => 'FSD-101',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-24 17:35:03',
                'updated_at' => '2026-07-24 18:33:58',
            ),
            99 => 
            array (
                'id' => 164,
                'project_id' => 1,
            'name' => 'Laporan Neraca (Balance Sheet)',
                'blueprint_code' => NULL,
                'brd_code' => 'BRD-079',
                'fsd_code' => 'FSD-079',
                'is_selected' => 1,
                'is_gap' => 0,
                'is_mandatory' => 0,
                'description' => 'Fitur produk standar ERP.',
                'created_at' => '2026-07-24 17:35:03',
                'updated_at' => '2026-07-25 04:56:41',
            ),
        ));
        
        
    }
}